POST http://localhost:3000/restart

###

POST http://localhost:3000/addplayer
Content-Type: application/json

{
    "name": "Joao"
}

###

POST http://localhost:3000/addplayer
Content-Type: application/json

{
    "name": "Jobim"
}

###

POST http://localhost:3000/addplayer
Content-Type: application/json

{
    "name": "Abognale"
}

###

POST http://localhost:3000/addplayer
Content-Type: application/json

{
    "name": "Bojangles"
}

###

POST http://localhost:3000/start

###

POST http://localhost:3000/bid
Content-Type: application/json

{
    "player": "Joao", "bid": ["Hearts", 7]
}

###

POST http://localhost:3000/bid
Content-Type: application/json

{
    "player": "Jobim", "bid": ["Clubs", 7]
}

###

POST http://localhost:3000/bid
Content-Type: application/json

{
    "player": "Abognale", "bid": ["Diamonds", 7]
}

###

POST http://localhost:3000/bid
Content-Type: application/json

{
    "player": "Bojangles", "bid": ["Diamonds", 5]
}

###

GET http://localhost:3000/players

###

GET http://localhost:3000/teams
